# Generated by Django 4.2.6 on 2023-10-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
    ]
